### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/DBI#3]
Example: RSQLite: 29%, coverage low especially on the C++ level

```
RSQLite Test Coverage: 29.02%
R/deprecated.R: 0.00%
R/extensions.R: 0.00%
R/SQLiteConnection.R: 0.00%
R/SQLiteDriver.R: 0.00%
R/SQLiteResult.R: 0.00%
R/zzz.R: 0.00%
src/extension-functions.c: 0.00%
src/rsqlite.cpp: 20.00%
src/sqlite3.c: 29.24%
R/RcppExports.R: 56.25%
src/RcppExports.cpp: 60.00%
src/result.cpp: 68.00%
src/connection.cpp: 68.42%
R/connect.R: 70.37%
R/transactions.R: 75.00%
R/query.R: 76.47%
R/table.R: 84.44%
R/datasetsDb.R: 100.00%
R/utils.R: 100.00%
```

**Comment by hadley** [comment]
From my perspective, the most important types of testing are:

* you can correctly input and output various data types, including characters with strange encodings, date times with time zones etc.

* inputs are correctly escaped, so that you are protected against SQL injection attacks (i.e. need to test with table and field names that require escaping)

**Comment by hadley** [comment]
FWIW I'd be happy to turn on code cov for all the repos if that would be helpful

**Comment by krlmlr** [comment]
codecov would definitely help, but in at least one project tests fail, so we won't have coverage there yet. I'll take a look.

**Comment by krlmlr** [comment]
@hadley Could you please turn coverage (http://codecov.io) for the four repos and review the PRs? All tests pass now.

**Comment by hadley** [comment]
I'm reasonably certain codecov doesn't need any explicit action from me to turn testing on - let me know if just merging the PRs isn't enough.

**Comment by krlmlr** [comment]
DBItest improves coverage.
